export interface Iskills {
    acrobatics: boolean;
    acrobaticsBonus: number;
    animalHandling: boolean;
    animalHandlingBonus: number
    arcana: boolean;
    arcanaBonus: number
    athletics: boolean
    athleticsBonus: number;
    deception: boolean;
    deceptionBonus: number;
    history: boolean;
    historyBonus: number;
    insight: boolean;
    insightBonus: number;
    intimidation: boolean;
    intimidationBonus: number;
    investigation: boolean;
    investigationBonus: number;
    medicine: boolean;
    medicineBonus: number;
    nature: boolean;
    natureBonus: number;
    perception: boolean;
    perceptionBonus: number;
    performance: boolean;
    performanceBonus: number;
    persuasion: boolean;
    persuasionBonus: number;
    religion: boolean;
    religionBonus: number;
    slightOfHand: boolean;
    slightOfHandBonus: number;
    stealth: boolean;
    stealthBonus: number;
    survival: boolean;
    survivalBonus: number;
}
