import { Stats } from './stats';
import { SavingThrows } from './saving-throws';
import { Skills } from './skills';
import { HP } from './hp';
import { Personality } from './personality';
import { AttacksAndSpellcasting } from './attacks-and-spellcasting';
import { Equipment } from './equipment';
import { OtherProficienciesAndLanguages } from './other-proficiencies-and-languages';
import { FeaturesAndTraits } from './features-and-traits';
import { SpellList } from './spell-list';

export class Character {
  characterName: string = "";
  characterClass: string = "";
  level: number = 0;
  exp: number = 0;
  background: string = "";
  race: string = "";
  alignment: string = "";
  playerName: string = "";
  expPoints: number = 0;
  stats = new Stats();
  inspiration: boolean = false;
  proficiencyBonus: number = 0;
  savingThrows = new SavingThrows();
  skills = new Skills();
  hp = new HP();
  personality = new Personality();
  attacksAndSpellcasting = new AttacksAndSpellcasting();
  passiveInvestigation: number = 0;
  passivePerception: number = 0;
  passiveInsight: number = 0;
  otherProficienciesAndLanguages = new OtherProficienciesAndLanguages();
  equipment = new Equipment();
  featuresAndTraits = new FeaturesAndTraits();
  spellcastingAbility: string = "";
  spellSaveDC: number = 0;
  spellAttackBonus: number = 0;
  spellList = new SpellList();
  classAttributes: Array<string> = [];
}